export const ENGLISH = [
  {
    id: "1",
    question: "I'm very happy _____ in India. I really miss being there.",
    optionA: "to live",
    optionB: "to have lived",
    optionC: "to be lived",
    optionD: "to be living",
    answer: "B",
    choice: "",
  },
  {
    id: "2",
    question: "He _____ the room and sat on the chair.",
    optionA: "was crossing",
    optionB: "has been crossing",
    optionC: "has crossed",
    optionD: "crossed",
    answer: "D",
    choice: "",
  },
  {
    id: "3",
    question: "It was past midnight, so there were _____ people in the street.",
    optionA: "few",
    optionB: "a few",
    optionC: "any",
    optionD: "less",
    answer: "A",
    choice: "",
  },
  {
    id: "4",
    question: "Continual means?",
    optionA: "going on without stopping",
    optionB: "occuring repeatedly all the time",
    optionC: "always",
    optionD: "never ending",
    answer: "A",
    choice: "",
  },
  {
    id: "5",
    question: "I am not older than you _____ ?",
    optionA: "aren't I",
    optionB: "amn't I",
    optionC: "weren't I",
    optionD: "am I",
    answer: "D",
    choice: "",
  },
  {
    id: "6",
    question: "It gives me immense pleasure _____ you to the party.",
    optionA: "to invite",
    optionB: "for invitation",
    optionC: "in inviting",
    optionD: "inviting",
    answer: "D",
    choice: "",
  },
  {
    id: "7",
    question: "Abstract noun of 'see' is?",
    optionA: "seeing",
    optionB: "saw",
    optionC: "seen",
    optionD: "sight",
    answer: "D",
    choice: "",
  },
  {
    id: "8",
    question: "_____ playing football, he plays cricket",
    optionA: "beside",
    optionB: "besides",
    optionC: "but",
    optionD: "also",
    answer: "B",
    choice: "",
  },
  {
    id: "9",
    question: "He took _____ with his work.",
    optionA: "troubles",
    optionB: "pains",
    optionC: "leave",
    optionD: "rest",
    answer: "A",
    choice: "",
  },
  {
    id: "10",
    question: "Which of the following words means 'understand' fully",
    optionA: "Apprehend",
    optionB: "Pretend",
    optionC: "Discuss",
    optionD: "Comprehend",
    answer: "D",
    choice: "",
  },
];
